name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21' # Change this to your required Java version
          distribution: 'temurin'

      - name: Build JAR (Windows)
        run: .\gradlew shadowJar

      - name: Package Distribution for Current OS (Windows)
        run: .\gradlew packageDistributionForCurrentOs

      - name: Create Distributable (Windows)
        run: .\gradlew createDistributable

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-files
          path: build/libs/*.jar

      - name: Upload Distribution
        uses: actions/upload-artifact@v4
        with:
          name: distribution-files
          path: build/distributions/*
